# - Try to find the Just Thread libraries
#
# JUSTTHREAD_FOUND - system has Just Thread installed
# JUSTTHREAD_INCLUDE_DIR - the Just Thread include directory
# JUSTTHREAD_LIBRARIES_DYNAMIC - Just Thread libraries (dynamic version)
# JUSTTHREAD_LIBRARIES_STATIC - Just Thread libraries (static version)

MESSAGE(STATUS "Looking for JUSTTHREAD...")

FIND_PATH(JUSTTHREAD_INCLUDE_DIR thread PATHS 
	/usr/include/justthread/
	)
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    FIND_LIBRARY(JUSTTHREAD_LIBRARIES_DYNAMIC NAMES libjustthread.so PATHS
    	/usr/lib64/
    	)
    FIND_LIBRARY(JUSTTHREAD_LIBRARIES_STATIC NAMES libjustthread.a PATHS
    	/usr/lib64/
    	)
ELSE()
    FIND_LIBRARY(JUSTTHREAD_LIBRARIES_DYNAMIC NAMES libjustthread.so PATHS
    	/usr/lib/
    	)
    FIND_LIBRARY(JUSTTHREAD_LIBRARIES_STATIC NAMES libjustthread.a PATHS
    	/usr/lib/
    	)
ENDIF()

IF(JUSTTHREAD_INCLUDE_DIR AND JUSTTHREAD_LIBRARIES_DYNAMIC AND JUSTTHREAD_LIBRARIES_STATIC)
	SET(JUSTTHREAD_FOUND 1)
	IF(NOT JUSTTHREAD_FIND_QUIETLY)
		MESSAGE(STATUS "Found JUSTTHREAD: libraries_dynamic = ${JUSTTHREAD_LIBRARIES_DYNAMIC}, libraries_static = ${JUSTTHREAD_LIBRARIES_STATIC}")
	ENDIF()
ELSE()
	SET(JUSTTHREAD_FOUND 0 CACHE BOOL "JUSTTHREAD not found")
	IF(JUSTTHREAD_FIND_REQUIRED)
	    MESSAGE(FATAL_ERROR "Could NOT find JUSTTHREAD, error")
	ELSE()
	    MESSAGE(STATUS "Could NOT find JUSTTHREAD, disabled")
	ENDIF()
	
ENDIF()

MARK_AS_ADVANCED(JUSTTHREAD_INCLUDE_DIR JUSTTHREAD_LIBRARIES_DYNAMIC JUSTTHREAD_LIBRARIES_STATIC)