# - Try to find the Thrift libraries
# Once done this will define
#
# THRIFT_FOUND - system has Thrift
# THRIFT_INCLUDE_DIR - the Thrift include directory
# THRIFT_LIBRARIES - Thrift library

IF(NOT WIN32)
    FIND_PATH(THRIFT_INCLUDE_DIR Thrift.h PATHS
        /usr/include/thrift
        /usr/local/include/thrift
        )
    FIND_LIBRARY(THRIFT_LIBRARIES thrift)
    FIND_PROGRAM(THRIFT_COMPILER thrift)
ENDIF()

#IF(THRIFT_INCLUDE_DIR AND THRIFT_LIBRARIES AND THRIFT_LIBRARIES_FPIC AND THRIFT_COMPILER)
IF(THRIFT_INCLUDE_DIR AND THRIFT_LIBRARIES AND THRIFT_COMPILER)
    SET(THRIFT_FOUND 1)
    IF(NOT THRIFT_FOUND_QUIETLY)
        MESSAGE(STATUS "Found THRIFT: include = ${THRIFT_INCLUDE_DIR}, libraries = ${THRIFT_LIBRARIES}, thrift_compiler ${THRIFT_COMPILER}")
    ENDIF()
ELSE()
    SET(THRIFT_FOUND 0 CACHE BOOL "THRIFT not found")
    MESSAGE(STATUS "THRIFT not found, disabled")
ENDIF()

MARK_AS_ADVANCED(THRIFT_INCLUDE_DIR THRIFT_LIBRARIES)

MESSAGE(" thrift header - ${THRIFT_INCLUDE_DIR} ")
